#!/usr/bin/python

import os
import sys
import subprocess
import urllib2
import json

cwd = (os.getcwd() + "/agile")

options = []
command = ""
parameters = []


def extract_options(s):
	for i in s:
		if i in 'abcdefghijklmnopqrstuvwxyz':
			options.append(i)


def colorize(text, color=None):
	if color == 'red':
		return '\033[1;31m' + text + '\033[0m'
	elif color == 'blue':
		return '\033[1;34m' + text + '\033[0m'
	elif color == 'green':
		return '\033[1;32m' + text + '\033[0m'
	elif color == 'yellow':
		return '\033[1;33m' + text + '\033[0m'
	elif color == 'magenta' or color == 'pink':
		return '\033[1;35m' + text + '\033[0m'
	elif color == 'cyan':
		return '\033[1;36m' + text + '\033[0m'
	else:
		return text


# Parse args into command, options, and parameters
for arg in sys.argv:
	if arg.startswith("-"):
		extract_options(arg)

	elif arg == cwd:
		continue

	elif not command:
		command = arg

	else:
		parameters.append(arg)


# Tasks
if command == "tasks":
	if not parameters:
		print "Fetching Tasks..."

		response = urllib2.urlopen('http://applify.sym.ph/api/v1/items')
		api_response = json.loads(response.read())
		items = api_response['data']['items']

		if items:
			count = 1
			for item in items:
				print colorize(str(item['id']) + '\t' + item['content'], 'red')
				count += 1
			print '\nFetched ' + str(count) + ' tasks.'
		else:
			print "No Tasks"

elif command == 'create':
	if not parameters:
		print "What do you want me to create? Missing parameter error."

	elif parameters[0] == 'task':
		try:
			task = parameters[1]
			print "Creating Task..."
			url = 'http://applify.sym.ph/api/v1/items'
			task_data = {
				"kind": "task",
				"content": parameters[1],
				"status": "done",
				"owner": "albert@sym.ph",
				"project": "5629499534213120",
				"tags": ["SAMPLE_TAG"]
			}
			data = json.dumps(task_data)
			req = urllib2.Request(url, data, {'Content-Type': 'application/json'})
			response = urllib2.urlopen(req)
			api_response = json.loads(response.read())
			response.close()
			print "Task Created!"

		except IndexError:
			print "What task do you want me to create? Please surround it with quotes."




# a = subprocess.check_output(["git", "branch"])
# b = a.splitlines()
# print a
# print b